# Generated by Django 3.2.7 on 2021-09-04 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, max_length=400, null=True)),
                ('name', models.CharField(blank=True, max_length=400, null=True)),
                ('key', models.CharField(blank=True, max_length=400, null=True, unique=True)),
                ('converted_link', models.URLField(blank=True, max_length=400, null=True)),
                ('count', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
