# Generated by Django 3.2.7 on 2021-09-04 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='entry',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
