# Generated by Django 3.2.7 on 2021-09-04 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_storage_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='entry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
