# Generated by Django 3.2.7 on 2021-09-04 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_storage_entry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storage',
            old_name='entry',
            new_name='date_time',
        ),
    ]
