# Generated by Django 3.2.7 on 2021-12-13 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_rename_entry_storage_date_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Storage',
            new_name='LinkStorage',
        ),
    ]
