# Generated by Django 3.2.7 on 2021-12-20 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_gallery_index_skill_testimonial_vertical'),
    ]

    operations = [

        migrations.AddField(
            model_name='event',
            name='completed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='index/testimonial'),
        ),
    ]
