# Generated by Django 3.2.7 on 2021-12-21 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20211221_1550'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
    ]
