# Generated by Django 3.2.7 on 2021-12-21 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20211221_0015'),
        ('dashboard', '0010_event_completed'),
    ]

    operations = [
    ]
