# Generated by Django 3.2.7 on 2021-12-21 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20211221_1553'),
        ('dashboard', '0010_delete_team'),
        ('dashboard', '0010_team'),
        ('dashboard', '0012_auto_20211221_1549'),
    ]

    operations = [
    ]
