# Generated by Django 4.0 on 2022-01-09 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_rename_about_us_headings_index_about_us_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='vertical',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verticals', to='dashboard.vertical'),
        ),
    ]
