# Generated by Django 3.2.7 on 2022-01-12 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_alter_company_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cover_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='event'),
        ),
    ]
