# Generated by Django 3.2.5 on 2022-01-13 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_startups'),
    ]

    operations = [
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=400, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='startup')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('about', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Startups',
        ),
    ]
