# Generated by Django 3.2.7 on 2022-01-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_index_startup_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ongoing',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='site_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
