# Generated by Django 3.2.5 on 2022-01-15 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_index_startup_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='liunkedin',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='url',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
