# Generated by Django 3.2.7 on 2022-01-17 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_auto_20220115_2339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startup',
            name='liunkedin',
        ),
        migrations.RemoveField(
            model_name='startup',
            name='url',
        ),
    ]
