# Generated by Django 3.2.10 on 2022-01-18 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_auto_20220115_2339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startup',
            name='liunkedin',
        ),
        migrations.RemoveField(
            model_name='startup',
            name='url',
        ),
        migrations.AddField(
            model_name='startup',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='site_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
