# Generated by Django 3.2.7 on 2022-02-20 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_auto_20220125_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='startup',
            old_name='name',
            new_name='founder_name',
        ),
        migrations.AddField(
            model_name='startup',
            name='founder_name2',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
