# Generated by Django 3.2.7 on 2022-02-20 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_auto_20220220_1510'),
    ]

    operations = [
        migrations.RenameField(
            model_name='startup',
            old_name='linkedin_url',
            new_name='linkedin_url_1',
        ),
        migrations.AddField(
            model_name='startup',
            name='linkedin_url_2',
            field=models.URLField(blank=True, null=True),
        ),
    ]
