# Generated by Django 3.2.7 on 2022-03-05 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0038_featured'),
    ]

    operations = [
        migrations.RenameField(
            model_name='featured',
            old_name='url',
            new_name='link',
        ),
    ]
